# Generated by Django 4.1.4 on 2023-01-16 17:45

import CSE.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('journal_name', models.CharField(max_length=255)),
                ('journal_article', models.FileField(upload_to='journals/', validators=[CSE.models.validate_pdf])),
                ('journal_doi', models.IntegerField()),
                ('ugc_listed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fac_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('conference_name', models.CharField(max_length=255)),
                ('conference_article', models.FileField(upload_to='conferences/', validators=[CSE.models.validate_pdf])),
                ('conference_doi', models.IntegerField()),
                ('ugc_listed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fac_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
