# Generated by Django 4.1.4 on 2023-01-19 13:47

import CSE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0003_remove_faculty_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conference_article',
            field=models.FileField(upload_to='pdf_files/', validators=[CSE.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_article',
            field=models.FileField(upload_to='pdf_files/', validators=[CSE.models.validate_pdf]),
        ),
    ]
