# Generated by Django 4.1.4 on 2023-01-19 14:02

import CSE.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0005_alter_conference_conference_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conference_article',
            field=models.FileField(upload_to='conf/', validators=[CSE.models.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_article',
            field=models.FileField(upload_to='journ/', validators=[CSE.models.validate_pdf]),
        ),
    ]
