# Generated by Django 4.1.4 on 2023-01-20 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CSE', '0009_faculty_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conference_doi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_doi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
